"""add favorite, deleted and timestamps to snippet

Revision ID: 1546a147697f
Revises: 78bdbbdca9e2
Create Date: 2026-07-26 15:30:10.714708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1546a147697f'
down_revision: Union[str, Sequence[str], None] = '78bdbbdca9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('snippets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('snippets', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippets', 'view_count')
    op.drop_column('snippets', 'is_deleted')
    op.drop_column('snippets', 'is_favorite')
    # ### end Alembic commands ###
